### 歩行者が歩行を開始する
POST http://localhost:8000/api/walking/start HTTP/1.1
content-type: application/json

{
    "pedestrianId": "01F8VYXK67BGC1F9RP1E4S9YAK",
    "floorId": "01F8VYXK67BGC1F9RP1E4S9YTV"
}


### 歩行者が歩行する
POST http://localhost:8000/api/walking/finish HTTP/1.1
content-type: application/json

{
    "trajectoryId": "01JEMZD09W2SWNSG8MGYC5JJYD"
}


### 歩行者が歩行を終了する
POST http://localhost:8000/api/walking/finish HTTP/1.1
content-type: application/json

{
    "trajectoryId": "01JEMZD09W2SWNSG8MGYC5JJYD"
}
