services:
  server:
    container_name: walking-information-walking-trajectory-storage-server
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    stdin_open: true
    ports:
      - 8000:8000
    networks:
      - walking-trajectory-storage-network

networks:
  walking-trajectory-storage-network:
    external: true
