[tool.ruff]
line-length = 100
indent-width = 4


[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN1",   # missing type self and cls
    "E999",   # syntax error
    "UP027",  # unpacked list comprehension
    "PT004",  # pytest missing fixture name underscore
    "PT005",  # pytest incorrect fixture name underscore
    "D1",     # undocumented
    "TD001",  # invalid todo tag
    "TD002",  # missing todo author
    "TD003",  # missing todo link
    "PD011",  # pandas use of dot values
    "INP001",
    "TRY301", # try except pass
    "N806",   # variable in except block
    "FBT001", # assert in finally block
    "D203",  # 1 blank line required before class docstring`
    "D212",  # Multi-line docstring summary should start at the second line
    "COM812", # missing space after comment hash
    "ISC001", # implicit string concatenation
    "N803",  # variable in except block
    "N815", # variable in except block
    "PLR0913", # prefer using f-strings
]
unfixable = [
    "F401",   # unused import
    "F841",   # unused variable
    "ERA001", # commented out code
]

logger-objects = ["src.library.logger.LOGGER"]

[tool.ruff.lint.pylint]
max-args = 6
