\c indoor_location_estimation;

CREATE TABLE floor_maps (
    id VARCHAR(26) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    floor_information_id VARCHAR(26) REFERENCES floor_information(id)
);

CREATE TABLE access_points (
    id VARCHAR(26) PRIMARY KEY,
    mac_address VARCHAR(17) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    floor_information_id VARCHAR(26) UNIQUE REFERENCES floor_information(id)
);

CREATE TABLE fp_models (
    id VARCHAR(26) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    access_point_id VARCHAR(26) UNIQUE REFERENCES access_points(id)
);

